name: update all playlists test

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:
  run-python:
    name: set up python and run YouTube.py
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.13'
      - name: pip install packages
        run: pip3 install -r requirements
      - name: setup settings.ini
        env:
          SETTINGS_INI: ${{ secrets.SETTINGS_INI }}
        run: |
          touch settins.ini
          echo "$SETTINGS_INI" > settings.ini
      - name: run YouTube.py
        run: |
          # Today's
          python3 YouTube.py --unlisted --playlist_update --playlist_regex "Today.*Top Hits" "Today Top Hits" spotify
          # Top 50 in Japan
          python3 YouTube.py --unlisted --playlist_update --playlist_regex "Top 50.*Japan" "Top 50 Japan" spotify
          # Top 50 in Global
          python3 YouTube.py --unlisted --playlist_update --playlist_regex "Top 50.*Global" "Top 50 Global" spotify
          # Top 50 in USA
          python3 YouTube.py --unlisted --playlist_update --playlist_regex "Top 50.*USA" "Top 50 USA" spotify
          # Top 50 in UK
          python3 YouTube.py --unlisted --playlist_update --playlist_regex "Top 50.*United Kingdom" "Top 50 United Kingdom" spotify

